name: ccsmethenv  # date 20230612
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.11
  - pip=23.1.2
  - pytorch::pytorch-cuda=11.8  # 11.8 is ok for 2.1.0, 2.0.1, 2.0.0
  - bedtools=2.30.0  # required by pybedtools
  - numpy=1.24.3
  - statsmodels=0.14.0
  - scikit-learn=1.2.2
  - pytorch::pytorch=2.1.0  # add channel prefix (pytorch::) to make sure the cuda version being installed?
  - pysam=0.21.0
  - tqdm=4.65.0
  - pybedtools=0.9.0
  - pytabix=0.1
  - scipy=1.10.1
  - pandas=2.0.2
  - samtools=1.17  # will install dependence->htslib, which includes tabix and bgzip
  - pbccs=6.4.0
  - pbmm2=1.13.1
  - minimap2=2.26
  - whatshap=1.7
  - parallel=20191122
  # - primrose>=1.3.0
  - pip:
    - ccsmeth==0.5.0
