name: ccsmethenv
channels:
  - bioconda
  - pytorch
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - cudatoolkit=10.2  # 11.0, 11.0.3, 10.2, 10.1, 9.2 for torch 1.7.0; 10.2 is ok for 1.7.0-1.11.0
  - bedtools=2.30.0  # required by pybedtools
  - numpy>=1.20.0
  - statsmodels>=0.13.2
  - scikit-learn>=1.0.2
  - pytorch::pytorch=1.11.0  # add channel prefix (pytorch::) to make sure the cuda version being installed?
  - pysam>=0.19.0
  - tqdm>=4.64.0
  - pybedtools>=0.8.1
  - pytabix>=0.1
  - scipy
  - pandas
  - samtools>=1.12  # will install dependence->htslib, which includes tabix and bgzip
  - pbccs>=6.4.0
  - pbmm2>=1.9.0
  - minimap2>=2.23
  - whatshap>=1.4
  - parallel=20191122
  # - primrose>=1.3.0
  - pip:
    - ccsmeth>=0.3.4
